# Generated by Django 4.1.7 on 2023-05-24 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosSensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('v1', models.FloatField()),
                ('v2', models.FloatField()),
                ('v3', models.FloatField()),
                ('v4', models.FloatField()),
                ('v5', models.FloatField()),
                ('v6', models.FloatField()),
                ('v7', models.FloatField()),
                ('v8', models.FloatField()),
                ('v9', models.FloatField()),
                ('v10', models.FloatField()),
                ('v11', models.FloatField()),
                ('v12', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idrandom', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=300)),
                ('relationUserProject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sensor', models.CharField(max_length=50)),
                ('red', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('relationUserTemplate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_Api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('relationUserDevice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
