# Generated by Django 4.1.7 on 2023-05-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='graphics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titlegraphics', models.CharField(max_length=1000)),
                ('namegraphics', models.CharField(max_length=1000)),
                ('aliasgraphics', models.CharField(max_length=1000)),
            ],
        ),
    ]
