# Generated by Django 4.1.7 on 2023-05-27 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project_Api', '0002_graphics'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics',
            name='relationUserGraphics',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='graphics', to=settings.AUTH_USER_MODEL),
        ),
    ]
