# Generated by Django 4.1.7 on 2023-05-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Api', '0003_graphics_relationusergraphics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphics',
            name='aliasgraphics',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='namegraphics',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='titlegraphics',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
